Create 2020-04-10-Jenkins.md
UCL-INGI/LEPL1503-Blog pull request #14
Opened 2020-04-10 10:45 UTC by tbary

Article permettant de configurer correctement jenkins. Discuté dans l'issue #3

2020-04-14 09:05 UTC, obonaventure requested changes

2020-04-14 09:05 UTC, obonaventure commented on _posts/2020-04-10-Jenkins.md
> +Jusqu'à présent, nous avons vu comment configurer Jenkins afin qu'il valide tout nouveau push effectué sur notre directory. Ici, nous allons voir comment lui faire effectuer différents tests qui perm
ou (sans accent) s'il introduit

2020-04-14 09:05 UTC, obonaventure commented on _posts/2020-04-10-Jenkins.md
> +Tout d'abord, il faut savoir que Jenkins NE PEUT PAS supprimer un push. Il peut seulement rejeter automatiquement une pull request lorsque celle-ci échoue aux tests. Il ne servira donc ici qu'à vérif
pouvez-vous mettre un lien vers la page moodle correspondante pour "Git et Jenkins tutoriel et projet exemple"  ?

2020-04-14 09:05 UTC, obonaventure commented on _posts/2020-04-10-Jenkins.md
> +Pour passer des commandes, rendez-vous sur jenkins dans l'onglet configure (configurer en français, à gauche avec le rouage) du job lié à votre projet. Allez dans la partie BUILD, dans la console de
Ce serait super d'ajouter une copie d'écran pour montrer l'onglet. Il est probablement possible de faire plusieurs copies d'écran pour cet article. Il suffit de les déposer dans le répertoire images et d'y faire référence (voyez le README.md pour un exemple)
Pour bash, merci d'indiquer [bash](http://man7.org/linux/man-pages/man1/bash.1.html)
idem pour rm
[rm](http://man7.org/linux/man-pages/man1/rm.1.html)
Pour make clean, merci d'indiquer ```make clean```
remplacer makefile par ```Makefile```

2020-04-14 09:05 UTC, obonaventure commented on _posts/2020-04-10-Jenkins.md
> +Ensuite, pour récupérer les résultats de vos tests, rendez-vous dans la partie "Actions à la suite du build" et sous "Ajouter une action après le build", sélectionner à chaque fois un "Publish..." au
la shell -> le shell
pour */, je mattrais ```*/``` et peut-être qu'une copie d'écran serait utile

2020-04-14 09:05 UTC, obonaventure commented on _posts/2020-04-10-Jenkins.md
> +Pour vérifier que tout fonctionne, rendez-vous sur votre répertoire gitlab et effectuez un push qui passe vos tests et un qui les échoue (cela fonctionne même avec un seul test échoué). Après quelque
une copie d'écran serait une excellente illustration

2020-04-14 09:05 UTC, obonaventure commented on _posts/2020-04-10-Jenkins.md
> +En espérant que tout ceci ait été utile,
je supprimerais ces deux lignes

2020-04-14 09:05 UTC, obonaventure commented on _posts/2020-04-10-Jenkins.md
> +Note : pour la compilation des programmes, il est nécessaire de rajouter l'option -std=c99 entre la mention gcc et le -o afin d'éviter une cascade d'erreurs de compilation une fois jenkins lancé.
Cette note devrait arriver plus haut si elle est importante. Elle me semble générique et pas liée à jenkins ?

2020-04-14 10:37 UTC, tbary commented on _posts/2020-04-10-Jenkins.md
> +Note : pour la compilation des programmes, il est nécessaire de rajouter l'option -std=c99 entre la mention gcc et le -o afin d'éviter une cascade d'erreurs de compilation une fois jenkins lancé.
Cette note me semble assez importante puisqu'elle a fait l'objet d'une séance entière de permanence où elle provoquait une erreur de compilation Jenkins chez de plusieurs étudiants... Je pense que je vais seulement la déplacer !

2020-04-14 11:26 UTC, tbary commented
@obonaventure Tout les changements désirés ont été faits ! N'hésitez pas à me faire savoir si vous voyez d'autres modification !

2020-04-18 18:06 UTC, tbary commented
@obonaventure j'ai fait les changements demandés ! peut-être n'avez-vous pas vu passer la notification...

2020-04-21 15:21 UTC, qdeconinck commented
@obonaventure a probablement pas vu votre update, je prends donc le relai.
La plupart des commentaires ont bien été intégrés, mais les images ne s'afficheront pas (vous vous en rendrez compte si vous tournez [jekyll](https://jekyllrb.com/docs/) en local.

Pourriez-vous juste corrigez ces liens en les préfixants par la variable `{{ site.baseurl }}` (par exemple, remplacer `![Configure](/images/ConfigureJenkins.PNG)` par `![Configure]({{ site.baseurl }}/images/ConfigureJenkins.PNG)`)?

Une fois fait, on mergera la PR.

2020-04-21 16:29 UTC, tbary commented
@qdeconinck les liens ont été update ! C'est étrange j'ai l'impression qu'il ne sont plus considérés comme de vrais liens sur github... est-ce normal ?

2020-04-22 07:46 UTC, qdeconinck approved these changes
Oui c'est normal, pas de problème avec ça.
Pour moi c'est bon

2020-04-22 07:48 UTC, obonaventure commented
Merci, j'étais occupé par des corrections de travaux et autres échéances, désolé du retard.

2020-04-22 07:49 UTC, merged