Makefile Variables post
UCL-INGI/LEPL1503-Blog pull request #16
Opened 2020-04-21 22:07 UTC by KafrouniChris

#12

2020-04-22 08:02 UTC, obonaventure requested changes

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +Ce sera plus simple à comprendre une fois que l'on se lance dans les examples..
un seul point après exEmples.

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +# Les Basics
Les bases

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +À savoir, la syntaxe est très importante, en effect le première élément avant **" : "** est le **target** et ceux après sont les dependances. Cela servira donc à l'outils make pour comprendre de quel
en effet pas en effect, je suggère de mettre (cible) après target
dependances -> dépendances
l'outils-> l'outil
quel manière -> quelle manière
objets -> objets

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +***Attention: la tabulation à la deuxième ligne est très importante pour la commande make!***
Je dirais que Makefile utilise l'indentation via une tabulation pour indiquer toutes les commandes à exécuter pour une cible donnée.

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +Pour l'instant, nous avons abordé la manière la plus basique d'écrire un makefile. pour chaque fichier on a du écrire deux lignes.. Pas très pratique tout ça. De plus que lorsque l'on compare les dif
makefile -> Makefile

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +On peut y remédier avec l'utilisation de variables comme dans nos programmes. On rajoute en haut de notre fichier toutes nos variables, et on peut les accéder comme dans le terminal avec $( *variable
les accéder -> y accéder

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +Pour plus d'informations en ce qui concerne les flags que l'on peut passé au compilateur [GCC](http://man7.org/linux/man-pages/man1/gcc.1.html) je vous redirige vers un autre post: [Quelques flags ut
passé -> passer

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +# Et les Variables Magiques ??
Et les variables magiques ?

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +Un example s'impose:
exemple

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +Avec le signe **%** . On ne doit plus réécrire les noms, et en une ligne on peut réécrire toutes les commandes servant à générer des fichier objects __.o.
objects -> objects

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +# Des commandes supplémentaire?
supplémentaires

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +**`make clean`**. Pour nettoyer ! ( pour effacer en une commande tous les fichier générés, le fichier **main** et les fichiers objects **__.o** et à peut prés tout ce que l'on veut.<br>
fichier main -> exécutable main

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +**`make clean`**. Pour nettoyer ! ( pour effacer en une commande tous les fichier générés, le fichier **main** et les fichiers objects **__.o** et à peut prés tout ce que l'on veut.<br>
à peu près

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +	rm -f *.xml  # Utile pour les fichier générer par valgrind et cppcheck
fichiers générés

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +Vous l'avez donc deviné, on peut donc créer toutes sortes de commandes executables en tapant `make <tartget-name>`
exécutables

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +En suivant ce que l'on a appris au point suivant, on peut créer une commande chargée d'effectuer tous nos tests avec par example **`make test`**<br>
exemple

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +On se rappelle que tous les fichiers __.o sont pris en charge par la commande vu plus haut. Donc pas besoins de rajouter une règle pour générer le fichier UnitTest.o supplémentaire.<br>
vu -> vue
besoins -> besoin

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +On n'oublis pas de rajouter une variable pour les flags requis par la librairie "CUnit".<br>
oublis -> oublie

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +Pour récapituler, la commande **`make test`** compile le fichier test, puis l'exécute, et finis par nettoyer le répertoire de tous les fichiers générés.
finis -> finit

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +À présent, le makefile ressemble à cela :
j'ajouterais un lien pour downloader le makefile complet. Vous pouvez le mettre dans le répertoire images

2020-04-22 08:02 UTC, obonaventure commented on _posts/2020-04-21-Makefile-Variables.md
> +Vous pouvez télécharger tous les fichiers crée dans cet article [ici](https://github.com/KafrouniChris/kafrounichris.github.io/tree/master/_posts/Makefile-Material).
copiez-le plutôt sur le blog pour qu'il persiste

2020-04-22 08:43 UTC, qdeconinck requested changes
Merci pour la PR. Toutefois il y a encore pas mal de soucis (formattage, orthographe, précisions,...) avant qu'on puisse accepter le post. Pourriez-vous les adresser et nous avertir quand les changements demandés seront effectifs?

Aussi, ça peut être utile de tester si la page fonctionne bien en local en installant [jekyll](https://jekyllrb.com/docs/).

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +Au cas où vous n'avez toujours pas eu l'occasion de faire vos premiers pas avec cet outil très puissant, laissez-moi vous introduire au Makefile.<br>
Pourquoi finir votre phrase par une balise br? Si vous voulez introduire un retour à la ligne, vous pouvez aussi mettre une ligne vide entre deux paragraphes

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +Ce sera plus simple à comprendre une fois que l'on se lance dans les examples..
deux points finaux

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +Un Makefile est un fichier contenant toutes les commandes que l'on aurait typiquement tapé dans le terminal pour compiler et lancer certaines parties de notre code. Les stocker dans ce fichier nous p
Idem qu'au dessus

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +# Les Basics
"Les Bases" plutôt non?

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +>>Makefile
Je me demande si une représentation "à la commande [tree](https://linux.die.net/man/1/tree)" ne donnerait pas mieux:
```
Tuto-Makefile
|- main.c
|- addition.c
|- multiplication.c
|- Makefile
```

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +```
L'effort pour mettre les codes en vis à vis est bien, mais il faut faire très attention à ne pas mélanger les espaces et les tabulations, sinon le rendu final sera illisible (la conversion tabulation -> nombre d'espaces visibles est variable)... Essayer de générez vos blancs uniquement avec des espaces (donc sans aucune tabulation)

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +```
Même remarque que ci-dessus

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +À savoir, la syntaxe est très importante, en effect le première élément avant **" : "** est le **target** et ceux après sont les dependances. Cela servira donc à l'outils make pour comprendre de quel
"le première" -> le premier
"en effect" -> en effet
"le **target**" -> la target ou la cible
"de quel manière" -> de quelle manière
"aux compilations" -> pour compiler le programme

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +Le fait d'écrire les ***règles*** de compilation de cette manière nous permet d'uniquement passer la commande `make` qui effectuera les trois opérations. <br>
Ca vaudrait la peine d'expliquer pourquoi dans cet ordre là, ça va fonctionner. C'est parce que la règle par défaut d'un makefile, sans la présence de la cible .DEFAULT_GOAL, c'est la première qui ne commence pas par un `.`

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +Pour l'instant, nous avons abordé la manière la plus basique d'écrire un makefile. pour chaque fichier on a du écrire deux lignes.. Pas très pratique tout ça. De plus que lorsque l'on compare les dif
"pour chaque fichier on a du écrire deux lignes.." -> Pour chaque fichier, on a dû écrire deux lignes.
"De plus que lorsque" -> De plus, lorsque
"beaucoup de répétions" -> "beaucoup de répétions de la commande `gcc`"

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +On peut y remédier avec l'utilisation de variables comme dans nos programmes. On rajoute en haut de notre fichier toutes nos variables, et on peut les accéder comme dans le terminal avec $( *variable
"avec $( *variable* )" -> avec la syntaxe $( *variable* )

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +Pour plus d'informations en ce qui concerne les flags que l'on peut passé au compilateur [GCC](http://man7.org/linux/man-pages/man1/gcc.1.html) je vous redirige vers un autre post: [Quelques flags ut
"l'on peut passé" -> l'on peut passer

Pour le lien vers l'autre post, je privilégie l'approche d'utiliser la variable jekyll magique {{ site.baseurl }} pour gérer le jour où l'on voudrait bouger le blog vers une autre adresse sans casser le lien, donc ça deviendrait
[Quelques flags utiles pour la compilation]({{ site.baseurl }}/gcc-flags/)

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +Le Makefile vient encore à notre secours car on a bien optimisé notre fichier, mais il y a encore beaucoup trop de lignes à mon goût, étant donné toutes les répétions.<br>
Ca vaudrait la peine d'expliciter les répétitions présentes, en l'occurence ici que la dépendance et la cible apparaisse aussi dans les commandes

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +* $@ permet d'accéder au nom du *target*
$@ -> `$@`
"du *target*" -> de la *target* ou de la cible

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +* $^ permet d'accéder aux noms des *dépendances* ( les fichiers après ":" )
$^ -> `$^`

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +* $< permet d'accéder au nom du premier fichier à la droite du ":"
$< -> `$<`

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +Un example s'impose:
example -> exemple

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +On peut d'autant plus voir les similitudes entres les lignes. Il y a sûrement une meilleure méthode pour écrire tout ça?<br>
"Il y a sûrement une meilleure méthode pour écrire tout ça?" -> si la phrase est rhétorique, alors il faut plutôt dire "Il y a sûrement une meilleure méthode pour écrire tout ça, non?"

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +Avec le signe **%** . On ne doit plus réécrire les noms, et en une ligne on peut réécrire toutes les commandes servant à générer des fichier objects __.o.
Je propose de d'abord introduire ce que fait `%` avant d'en venir aux conséquences, le début ici suggère que  `%` est "magique" avant d'expliquer ce que ça fait

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +# Des commandes supplémentaire?
Des commandes supplémentaire? -> supplémentaires

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +**`make clean`**. Pour nettoyer ! ( pour effacer en une commande tous les fichier générés, le fichier **main** et les fichiers objects **__.o** et à peut prés tout ce que l'on veut.<br>
"à peut prés" -> à peu près
Attention, il manque une parenthèse fermante

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +	rm main *.o
Et quid si on fait `make clean` avant les autres commandes? Je ne pense pas que la commande devrait échouer... Pour éviter que `rm``échoue, ça peut valoir la peine de mettre le flag `-f` (comme la commande ci-dessous) et expliquer pourquoi il est utile

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +Vous l'avez donc deviné, on peut donc créer toutes sortes de commandes executables en tapant `make <tartget-name>`
toutes sortes de commandes executables -> toute sorte de séquences de commandes exécutables

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +## UnitTests
Tests Unitaires

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +En suivant ce que l'on a appris au point suivant, on peut créer une commande chargée d'effectuer tous nos tests avec par example **`make test`**<br>
au point suivant -> au point précédent
par example -> par exemple

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +>>UnitTest.c
Idem qu'au début

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +On peut donc rajouter
... dans le Makefile

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +On se rappelle que tous les fichiers __.o sont pris en charge par la commande vu plus haut. Donc pas besoins de rajouter une règle pour générer le fichier UnitTest.o supplémentaire.<br>
tous les fichiers __.o -> c'est pas plutôt "tous les fichiers ***.o**"?
"pas besoins" -> pas besoin

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +On n'oublis pas de rajouter une variable pour les flags requis par la librairie "CUnit".<br>
On n'oublis -> On n'oublie
rajouter une variable : laquelle?

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +Pour récapituler, la commande **`make test`** compile le fichier test, puis l'exécute, et finis par nettoyer le répertoire de tous les fichiers générés.
"finis" -> finit

2020-04-22 08:43 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +Vous pouvez télécharger tous les fichiers crée dans cet article [ici](https://github.com/KafrouniChris/kafrounichris.github.io/tree/master/_posts/Makefile-Material).
tous les fichiers crée -> créés

2020-04-22 11:52 UTC, KafrouniChris commented on _posts/2020-04-21-Makefile-Variables.md
> +>>Makefile
Oui il me semble que vous avez raison, j'ai commencé par cette représentation, puis j'ai changé pensant embellir le texte.

Merci pour le feedback!

2020-04-22 12:36 UTC, KafrouniChris commented on _posts/2020-04-21-Makefile-Variables.md
> +Le Makefile vient encore à notre secours car on a bien optimisé notre fichier, mais il y a encore beaucoup trop de lignes à mon goût, étant donné toutes les répétions.<br>
Parfait merci!

2020-04-22 13:35 UTC, KafrouniChris commented on _posts/2020-04-21-Makefile-Variables.md
> +Vous pouvez télécharger tous les fichiers crée dans cet article [ici](https://github.com/KafrouniChris/kafrounichris.github.io/tree/master/_posts/Makefile-Material).
Est-ce que vous savez comment faire pour rediriger le lien vers le repo? 
J'ai vu dans la documentation, l'utilisation de la variable `site.github.url`.
Par contre elle n'a pas l'aire de fonctionner correctement. 

... dans cet article \[ici]({{site.github.url}}/images/makefile_post)
... dans cet article [ici]({{site.github.url}}/images/makefile_post)

2020-04-22 13:51 UTC, KafrouniChris commented on _posts/2020-04-21-Makefile-Variables.md
> +Vous pouvez télécharger tous les fichiers crée dans cet article [ici](https://github.com/KafrouniChris/kafrounichris.github.io/tree/master/_posts/Makefile-Material).
Par contre je ne sais pas si l'utilisation de "/tree/master/" dans l'url pourrait poser problème.

2020-04-22 14:03 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +Vous pouvez télécharger tous les fichiers crée dans cet article [ici](https://github.com/KafrouniChris/kafrounichris.github.io/tree/master/_posts/Makefile-Material).
Je ne sais pas si c'est utile de mettre le lien du github du blog, vu que quelque part, elle se référence elle-même

2020-04-22 14:06 UTC, qdeconinck commented on _posts/2020-04-21-Makefile-Variables.md
> +Vous pouvez télécharger tous les fichiers crée dans cet article [ici](https://github.com/KafrouniChris/kafrounichris.github.io/tree/master/_posts/Makefile-Material).
J'ai rien dit, ça me semble OK, par contre je mettrai le code dans un nouveau dossier "code", plutôt que le dossier "images"

2020-04-22 15:15 UTC, KafrouniChris commented on _posts/2020-04-21-Makefile-Variables.md
> +Vous pouvez télécharger tous les fichiers crée dans cet article [ici](https://github.com/KafrouniChris/kafrounichris.github.io/tree/master/_posts/Makefile-Material).
J'ai mis le dossier dans "images" suite à la demande de M. Bonaventure.

Je peux quand même changer si nécessaire.

2020-04-26 09:35 UTC, obonaventure approved these changes
Merci pour cette mise à jour

2020-04-26 09:35 UTC, merged