New post -> timer pour mesure de performance
UCL-INGI/LEPL1503-Blog pull request #18
Opened 2020-04-24 14:17 UTC by aknockaert

Ajout d'un post sur la création d'un timer automatisant la mesure de performance d'un programme multithreadé C.

2020-04-26 09:46 UTC, obonaventure requested changes
Bon post de blog, j'ai quelques suggestions pour l'améliorer. Merci

2020-04-26 09:46 UTC, obonaventure commented on _posts/2020-04-24-timer.md
> +La première boucle `for` s'occupe de lancer les `th` threads. La fonction execute retourne le temps pris par l'exécution et nous stockons cette info dans le tableau `temps`.
execute -> `execute`

2020-04-26 09:46 UTC, obonaventure commented on _posts/2020-04-24-timer.md
> +    if(pid == 0){ //fils
merci de vérifier si fork retourne -1

2020-04-26 09:46 UTC, obonaventure commented on _posts/2020-04-24-timer.md
> +Ici, la partie subtile est l'utilisation de la méthode `fork` qui permet de lancer un nouveau processus. Je ne rentre pas dans les détails, mais chaque processus possède un PID qui permet à l'OS de l
méthode -> appel système
fork -> [fork](http://man7.org/linux/man-pages/man2/fork.2.html)

2020-04-26 09:46 UTC, obonaventure commented on _posts/2020-04-24-timer.md
> +    arg[4] = (char*) malloc(3);
merci de tester la valeur de retour de malloc

2020-04-26 09:46 UTC, obonaventure commented on _posts/2020-04-24-timer.md
> +    sprintf(arg[4], "%d", i);
snprintf est préférable à sprintf, même si c'est plus ennuyeux à utiliser

2020-04-26 09:46 UTC, obonaventure commented on _posts/2020-04-24-timer.md
> +Ici, on va lancer le nouveau processus avec la fonction `execve`. Le premier paramètre est le nom de l'exécutable (`./fact` dans le cadre de ce cours), le second la liste des arguments à passer à l'e
fonction -> appel système
execve -> [execve](http://man7.org/linux/man-pages/man2/execve.2.html)

pour gettimeofday, ce serait bien de mentionner qu'elle a potentiellement une granularité de millisecondes et de pointer vers http://man7.org/linux/man-pages/man2/gettimeofday.2.html

2020-04-26 09:46 UTC, obonaventure commented on _posts/2020-04-24-timer.md
> +
La première exécution risque d'être un peu plus lente que les autres car l'exécutable n'est pas nécessairement en cache, je ferais un calcul non mesuré pour précharger la cache disque 
Entre deux mesures, j'ajouterais un petit délai avec un sleep
Au niveau de la sortie des résultats, je ferais une sortie en format CSV pour que ce soit facile à plotter par après

2020-04-26 12:16 UTC, aknockaert commented
Merci pour vos commentaires forts utiles.
Voici la version mise à jour.

2020-04-27 07:18 UTC, qdeconinck requested changes
Bonne PR, juste quelques problèmes de formattage à régler et ça sera bon.

2020-04-27 07:18 UTC, qdeconinck commented on _posts/2020-04-24-timer.md
> +# Coder un timer pour son programme multithreadé
L'ajout du header de jekyll est nécessaire pour ne pas casser le formattage du post (qui rendra sinon comme du simple HTML, ce qui est de suite beaucoup moins joli). Donc il faudrait retirer cette ligne de titre pour la remplacer par les suivantes (retirer les "", c'est pour éviter que github ne formatte le texte ci-dessous) :

"---
layout: post
title: Coder un timer pour son programme multithreadé
author: Antoine Knockaert
---"

2020-04-27 07:18 UTC, qdeconinck commented on _posts/2020-04-24-timer.md
> +Si vous ne voulez pas vous ennuyer à lire les explications, la version du code en entier sera disponible à la fin de ce post.
sera -> est

2020-04-27 07:18 UTC, qdeconinck commented on _posts/2020-04-24-timer.md
> +Description des variables :
Il faut rajouter une ligne blanche entre "Description des variables:" et le tableau, sinon le tableau ne se formatte pas... Les suggestions ci-dessous par rapport au tableau sont facultatives et donne un meilleur formatage selon moi.

2020-04-27 07:18 UTC, qdeconinck commented on _posts/2020-04-24-timer.md
> +| Variable | utilité |
Remplacer par (retirer les "" et ne pas prendre en compte les guillemets code)
`"| **Variable** | **Utilité** |"`

Les "**" mettent en gras, utilité en majuscule

2020-04-27 07:18 UTC, qdeconinck commented on _posts/2020-04-24-timer.md
> +| -------- | ------- |
Suggestion, centrer le contenu ci-dessous en remplaçant cette ligne par
`"| :------: | :-----: |"`

2020-04-27 07:18 UTC, qdeconinck commented on _posts/2020-04-24-timer.md
> +Dès lors, si la valeur que `fork` retourne est 0, nous sommes le processus nouvellement créé qui doit exécuter notre programme multithreadé. Si elle retourne autre chose, nous nous trouvons dans le p
"que le fils ai fini" -> "que le fils ait fini"

2020-04-27 07:18 UTC, qdeconinck commented on _posts/2020-04-24-timer.md
> +    arg[4] = (char*) malloc(3);
Ou au lieu de faire un malloc, pourquoi ne pas utiliser un tableau de char sur la stack? Ce n'est pas important, mais aussi un commentaire sur le pourquoi 3

2020-04-27 08:17 UTC, aknockaert commented on _posts/2020-04-24-timer.md
> +    arg[4] = (char*) malloc(3);
J'avoue qu'il n'y a pas vraiment de raison particulière au choix d'allouer la mémoire sur le Heap plutôt que la Stack. Est-ce que le tableau de char sur la Stack est préférable?
Le 3 est arbitraire aussi, nous permettant de placer des nombres allant de 1 à 999 (à priori, pas trop d'utilité à tester son code avec plus de threads... Mais cette limite devrait être mentionnée quelque part effectivement).

2020-04-27 08:22 UTC, qdeconinck commented on _posts/2020-04-24-timer.md
> +    arg[4] = (char*) malloc(3);
Probablement, mais à tester. Parce que le malloc créera une fuite de mémoire aussi, mais à vérifier si à mettre sur la stack ne pose pas de problème.
Aussi, si malloc vaut 3, on ne peut mettre que jusqu'à 99 (ne pas oublier le '\0').

2020-04-27 08:30 UTC, aknockaert commented on _posts/2020-04-24-timer.md
> +    arg[4] = (char*) malloc(3);
Oui pardon, j'ai effectivement oublié le \0 ! Donc de 1 à 99.
Je peux modifier le malloc pour y mettre :
char tab[3];
arg[4] = tab;
Le code fonctionne comme cela, il n'y a rien d'autre à changer à priori.

2020-04-27 08:37 UTC, qdeconinck approved these changes
Alors pour moi c'est bon. @obonaventure ?

2020-04-27 08:45 UTC, aknockaert commented
Je viens de rajouter l'explication du "pourquoi char tab[3]", de manière à prévenir qu'il faut augmenter cette valeur si on veut lancer les processus avec un nombre de threads supérieur à 99.
Je n'ai plus rien à modifier pour le moment, merci pour vos remarques.

2020-04-27 09:11 UTC, obonaventure approved these changes
Parfait pour moi, merci

2020-04-27 09:11 UTC, obonaventure commented
Merci pour cette contribution au blog

2020-04-27 09:14 UTC, merged