Article sur les Threads à plusieurs arguments
UCL-INGI/LEPL1503-Blog pull request #21
Opened 2020-04-28 10:16 UTC by wiauxb

2020-04-28 10:26 UTC, obonaventure requested changes

2020-04-28 10:26 UTC, obonaventure commented on _posts/2020-04-28-threadsMultiArgs.md
> +Seulement un problème se pose, votre fonction prend trois arguments et la foncion `pthread_create` refuse de la prendre ! En cherchant un peu, on peut se rendre compte que c'est normal, car la foncti
défini -> définie

2020-04-28 10:26 UTC, obonaventure commented on _posts/2020-04-28-threadsMultiArgs.md
> +- `(*start_routine)`: c'est ce que vous allez réellement écrire en argument, celà représente simplement un pointeur vers votre fonction.
celà -> cela

2020-04-28 10:26 UTC, obonaventure commented on _posts/2020-04-28-threadsMultiArgs.md
> +> Mais comment gérer un seul pointeur _void_ ? Ma fonction à besoin de trois arguments de types différent !
A besoin de trois arguments de types différentS

2020-04-28 10:26 UTC, obonaventure commented on _posts/2020-04-28-threadsMultiArgs.md
> +L'exemple que je viens de vous donner est simpliste, mais en utilisant le même stratagème que pour les arguments, vous pourriez retourner des structures de données aussi complexes que vous le désirer
Je suggère un exemple un peu plus complexe:
fonction minmax qui prend trois arguments double et retourne une structure contenant le min et le max de façon à couvrir en un seul exemple les arguments et les valeurs de retour

2020-04-28 12:06 UTC, wiauxb commented on _posts/2020-04-28-threadsMultiArgs.md
> +L'exemple que je viens de vous donner est simpliste, mais en utilisant le même stratagème que pour les arguments, vous pourriez retourner des structures de données aussi complexes que vous le désirer
Oui je comprend, je règle ça ce soir après les cours ;)

2020-04-28 16:47 UTC, wiauxb commented on _posts/2020-04-28-threadsMultiArgs.md
> +L'exemple que je viens de vous donner est simpliste, mais en utilisant le même stratagème que pour les arguments, vous pourriez retourner des structures de données aussi complexes que vous le désirer
J'ai écris le nouvel exemple, correspond-t-il à votre attente ?

2020-04-29 07:20 UTC, qdeconinck requested changes
Quelques suggestions pour améliorer votre post

2020-04-29 07:20 UTC, qdeconinck commented on _posts/2020-04-28-threadsMultiArgs.md
> +Seulement un problème se pose, votre fonction prend trois arguments et la foncion `pthread_create` refuse de la prendre ! En cherchant un peu, on peut se rendre compte que c'est normal, car la foncti
la foncion `pthread_create` -> fonction

2020-04-29 07:20 UTC, qdeconinck commented on _posts/2020-04-28-threadsMultiArgs.md
> +Pas de panique c'est en réalité assez simple. Nous allons créer une structure contenant tous vos arguments avec le bon type, et ensuite caster le pointer de cette structure en `void *`. De cette faço
caster le pointer -> caster le pointeur

2020-04-29 07:20 UTC, qdeconinck commented on _posts/2020-04-28-threadsMultiArgs.md
> +
Ca vaudrait la peine d'étendre un peu l'exemple avec les appels à `pthread_create` mais surtout à `pthread_join` pour récupérer l'argument, et éventuellement montrer son `free()`.

2020-04-29 10:43 UTC, wiauxb commented on _posts/2020-04-28-threadsMultiArgs.md
> +
j'ai rajouté une partie à propos du main et comment créer et join le thread mais je ne sais pas à quel point je dois aller dans le détail ...

2020-05-04 14:40 UTC, obonaventure approved these changes

2020-05-04 14:40 UTC, merged