Fonctions en BASH
UCL-INGI/LEPL1503-Blog pull request #22
Opened 2020-04-28 14:07 UTC by boucqueymat

Bonjour, 
Voici mon article sur les fonctions en BASH avec les améliorations que vous m'aviez suggérées.
Bien à vous, 
Matthieu Boucquey

2020-04-28 14:45 UTC, obonaventure requested changes

2020-04-28 14:45 UTC, obonaventure commented on _posts/27_04_2020_Fonctions_BASH.md
> +Vous avez sûrement déjà perdu patience à retaper « bêtement » des instructions dans votre terminal. Bien qu’existent des petits raccourcis (EX : fléche du haut) pour récupérer des instructions précéd
pour les raccourcis, vous pouvez faire un lien vers https://ucl-ingi.github.io/LEPL1503-Blog/arrows/

2020-04-28 14:45 UTC, obonaventure commented on _posts/27_04_2020_Fonctions_BASH.md
> +A l'intérieur des fonctions, les arguments sont accessibles par les appels **"$1"**, **"$2"**, ...
je supprimerais "les appels"

2020-04-28 14:45 UTC, obonaventure commented on _posts/27_04_2020_Fonctions_BASH.md
> +Ici, les éléments de la liste sont assignés, les uns après les autres, à la variable `var`. A chaque itération, les commandes entre `do` et `done` sont executées.
je pense qu'il faudrait d'abord expliquer ce qu'est une liste en bash

2020-04-28 14:45 UTC, obonaventure commented on _posts/27_04_2020_Fonctions_BASH.md
> +Voici un exemple concret lié à la réalisation de notre projet. La fonction **`timing`** prenant comme argument le nombre de threads de calcul indique le temps d'execution *(ainsi que d'autres mesures
executable -> exécutable

2020-04-28 14:45 UTC, obonaventure commented on _posts/27_04_2020_Fonctions_BASH.md
> +* La commande `command` permet d'écraser le mot clé `time` fourni par le shell bash au profit de la [véritable commande][3] `time` davantage modulable. *Petit test:* `type time` *VS* `type command ty
pouvez-vous mettre un lien vers [time](http://man7.org/linux/man-pages/man1/time.1.html) pour time

2020-04-28 14:45 UTC, obonaventure commented on _posts/27_04_2020_Fonctions_BASH.md
> +**PRATIQUE:** *Voici [un debugger][4] pour corriger de manière interactive vos scripts.*
Je dirais que shell check est un analyseur statique comme cppcheck, pas un debugger

2020-04-28 14:45 UTC, obonaventure commented on _posts/27_04_2020_Fonctions_BASH.md
> +**PRATIQUE:** *Voici [un debugger][4] pour corriger de manière interactive vos scripts.*
On pourrait mettre une phrase. En C il est intéressant d'utiliser cppcheck pour avoir un feedback sur son code C. En shell, l'outil [shellcheck](...) offre des fonctionnalités similaires.

2020-04-28 14:45 UTC, obonaventure commented on _posts/27_04_2020_Fonctions_BASH.md
> +**ASTUCE:** *Il est probable que vous aillez à modifier les permissons (ici, d'execution) du fichier créé. Il suffit d'entrer la commande* `chmod +x timing.sh` *pour rendre l'execution du fichier .sh
execution -> exécution

2020-04-29 07:12 UTC, qdeconinck requested changes
Très bon post, pour moi deux commentaires (dont un important):
1- Renommez le fichier en `2020-04-27-fonctions-bash.md`. Autrement, [jekyll](https://jekyllrb.com/docs/) ne va pas considérer votre post et celui-ci ne sera donc pas visible...
2- C'est bien de discuter de mettre une fonction dans un fichier .sh, je me demande si ça peut aussi valoir la peine de mentionner rapidement .bashrc ou .profile pour avoir une commande toujours disponible dans le shell

2020-04-29 07:12 UTC, qdeconinck commented on _posts/27_04_2020_Fonctions_BASH.md
> +# Fonctions en BASH
Retirez ce titre et mettez le header jekyll suivant, sinon votre post va être très mal formatté sur le site... (sans les guillemets, c'est pour que github ne formatte pas le texte)
"---
layout: post
title: Fonctions en BASH
author: Matthieu Boucquey
---"

2020-04-29 07:12 UTC, qdeconinck commented on _posts/27_04_2020_Fonctions_BASH.md
> +[5]: https://ucl-ingi.github.io/LEPL1503-Blog/arrows/
Remplacez ce lien par
[5]: {{ site.baseurl }}/arrows/

Ca rendra votre lien résilient si un jour on migre le site vers une autre URL

2020-04-29 07:12 UTC, qdeconinck commented on _posts/27_04_2020_Fonctions_BASH.md
> +Vous avez sûrement déjà perdu patience à retaper « bêtement » des instructions dans votre terminal. Bien qu’existent des [raccourcis][5] (EX : fléche du haut) pour récupérer des instructions précéden
(EX : fléche du haut) -> (par exemple, flèche du haut,...)
**Les fonctions en language BASH** -> **les fonctions en language BASH**

2020-04-29 07:12 UTC, qdeconinck commented on _posts/27_04_2020_Fonctions_BASH.md
> +* https://ucl-ingi.github.io/LEPL1503-Blog/arrows/
Idem que ci-dessus
{{ site.baseurl }}/arrows/

2020-04-29 09:17 UTC, boucqueymat commented
J'ai rajouté les améliorations suggérées! Pouvez-vous néanmoins vérifier que je n'ai pas dit de bêtises dans la mini introduction aux fichiers .bashrc et .profile? MERCI

2020-04-29 10:30 UTC, boucqueymat commented
De plus, les liens vers les 2 articles du blog, inaccessibles dans l'état actuel,  seront-ils opérationnels une fois l'article posté?

2020-05-04 14:29 UTC, obonaventure approved these changes

2020-05-04 14:29 UTC, obonaventure commented on _posts/27-04-2020-Fonctions-BASH.md
> +**ATTENTION:** *les arguments ne doivent pas être indiqués dans les paranthèses lors de la définition de la fonction.*
parEnthèses

2020-05-04 14:29 UTC, obonaventure commented on _posts/27-04-2020-Fonctions-BASH.md
> +Vous avez sûrement déjà perdu patience à retaper « bêtement » des instructions dans votre terminal. Bien qu’existent des [raccourcis][5] (par exemple, fléche du haut) pour récupérer des instructions
Merci d'utiliser la notation [lien](URL) pour les liens plutôt que des notes de fin de page

2020-05-04 14:29 UTC, obonaventure commented on _posts/27-04-2020-Fonctions-BASH.md
> +**REMARQUE:** *Ici les [listes][6] ont été introduites. En bash, une liste est initialisée en enfermant entre paranthèses ses éléments, séparés d'un espace.*
parEnthèses

2020-05-04 14:29 UTC, obonaventure commented on _posts/27-04-2020-Fonctions-BASH.md
> +* Avant de prendre des mesures sur l'executable `fact`, il est recommandé de l'executer une première fois. *(Fact se trouve alors dans la cache du [filesystem][1])*. Ceci permet d'éviter que systémat
exécutable

2020-05-04 14:29 UTC, obonaventure commented on _posts/27-04-2020-Fonctions-BASH.md
> +* La commande `command` permet d'écraser le mot clé `time` fourni par le shell bash au profit de la [véritable commande][3] `time` davantage modulable. *Petit test:* `type time` *VS* `type command ty
véritable commande -> utilitaire

2020-05-04 14:29 UTC, obonaventure commented on _posts/27-04-2020-Fonctions-BASH.md
> +Il est donc préférable de l'insérer dans un fichier .sh, autrement appelé **script**. Repenant l'exemple ci-dessus, voici le contenu du fichier **`timing.sh`** *(situé dans le même répertoire que vot
RepRenant

2020-05-04 14:29 UTC, obonaventure commented on _posts/27-04-2020-Fonctions-BASH.md
> +**ASTUCE:** *Il est probable que vous aillez à modifier les permissons (ici, d'execution) du fichier créé. Il suffit d'entrer la commande* `chmod +x timing.sh` *pour rendre l'execution du fichier .sh
permissIons  exécution

2020-05-04 14:29 UTC, obonaventure commented on _posts/27-04-2020-Fonctions-BASH.md
> +**POUR INFO:** *A noter que les [fichiers][8]* `.sh` *ne sont pas propre au shell BASH (d'ailleurs, il a fallu indiquer à ce fichier le shell à utiliser* `#!/bin/bash`*). Il existe un type de fichier
je ne mettrais pas interactive pour .bashrc

2020-05-04 14:29 UTC, obonaventure commented on _posts/27-04-2020-Fonctions-BASH.md
> +Bien entendu, ceci n'est qu'une introduction aux fonctions en BASH et celle-ci n'attend qu'à être approfondie. Je vous invite vivement à vous documenter pour dénicher peut-être d'autres astuces facil
exécution

2020-05-04 14:43 UTC, qdeconinck approved these changes
Je confirme que les liens marqués avec la balise {{ site.baseurl }} fonctionnent bien. Le format est bon, juste corriger les derniers points soulevés par @obonaventure et c'est bon.

2020-05-04 16:15 UTC, obonaventure approved these changes

2020-05-04 16:15 UTC, merged