Optimisation du nombre de threads au moyen de python
UCL-INGI/LEPL1503-Blog pull request #25
Opened 2020-05-05 10:22 UTC by Eliot-P

Bonjour,

voici la pull request concernant mon post. Pour ce qui est du lien web vers l'import de librairie, chaque import mentionné dans l'article est un lien vers la page de la librairie même.

Bonne journée
Eliot Peeters

2020-05-05 15:02 UTC, obonaventure requested changes
Merci pour ce post, quelques suggestions dans cette review

2020-05-05 15:02 UTC, obonaventure commented on _posts/2020-05-05-Python_graph.md
> +> [*os*](https://docs.python.org/3/library/os.html)
Cela pourrait être intéressant d'avoir un petit commentaire pour chaque librairie en disant à quoi elle sert

2020-05-05 15:02 UTC, obonaventure commented on _posts/2020-05-05-Python_graph.md
> +Pour cette version, le principe est d'exécuter le programme C dans le terminal au moyen de python. Donc pour peu que l'exectuable soit de la forme **./fact [-N nombre_de_threads] fichier_input fichie
verSion

2020-05-05 15:02 UTC, obonaventure commented on _posts/2020-05-05-Python_graph.md
> +### Exectuion version C
Exécution directe du code C

2020-05-05 15:02 UTC, obonaventure commented on _posts/2020-05-05-Python_graph.md
> +Une fois cette librairie créée, nous pouvos directement l'importer dans python au moyen de ces lignes définissant les variables globales dans notre programme :
pouvoNs

2020-05-05 15:02 UTC, obonaventure commented on _posts/2020-05-05-Python_graph.md
> +Une fois cette librairie créée, nous pouvos directement l'importer dans python au moyen de ces lignes définissant les variables globales dans notre programme :
définissant des références globales

2020-05-05 15:02 UTC, obonaventure commented on _posts/2020-05-05-Python_graph.md
> +Maintenant, il est possible d'appeler n'importe quel fonction de programme C dans python au moyen de la ligne de code :
quelLe fonction dU programme C en python

2020-05-05 15:02 UTC, obonaventure commented on _posts/2020-05-05-Python_graph.md
> +Il est à noter qu'ici le temps est directement mesurer en Python car passer par [*gettimeofday(3P)*](http://man7.org/linux/man-pages/man3/gettimeofday.3p.html) ne nous lit pas des valeurs correctes l
mesuré
ai -> ait
merci de mettre une référence explicite à l'autre article de blog

2020-05-05 15:02 UTC, obonaventure commented on _posts/2020-05-05-Python_graph.md
> +On écrit maintenant une fonction qui prend pour arguments le nombre de threads maximum et le nombre d'exéctuions du programme pour **n** threads :
exécUtions

2020-05-05 15:02 UTC, obonaventure commented on _posts/2020-05-05-Python_graph.md
> +Et finalement il ne nous reste plus qu'à écrire la fonction [*grapher()*]() qui prend pour argument l'array des temps d'executioné et retourne un graphique. Il s'agit uniquement de fonctions matplotl
d'exécution

2020-05-05 15:02 UTC, obonaventure commented on _posts/2020-05-05-Python_graph.md
> +Voici le graphique obtenu. En vert on peut voir le temps d executioé maximum et minimum observés lors des **X** exéctuions pour **n** threads et en bleu la moyenne du temps mis pour **n** threads, et
les temps d'exécution
graphE
encontrée -> Rencontrées
l'exécution du programme

2020-05-05 15:29 UTC, Eliot-P commented
Bonjour,

j'ai apporté les changements requis.

Bonne journée
Eliot Peeters

2020-05-07 07:02 UTC, obonaventure approved these changes

2020-05-07 07:02 UTC, merged