Blog post (alias) created
UCL-INGI/LEPL1503-Blog pull request #7
Opened 2020-04-08 12:32 UTC by dhoutart

2020-04-08 15:04 UTC, obonaventure requested changes

2020-04-08 15:04 UTC, obonaventure commented on _posts/2020-04-08-Alias.md
> +L'utilisation des _**alias**_ dans le shell (bash pour les explications qui suivent) est un outil à connaître absolument par la simplicité de sa mise en place et par le temps qu'il fait gagner quand
Ce serait bien de mettre [bash](http://man7.org/linux/man-pages/man1/bash.1.html) pour avoir un lien vers la page de manuel officielle

2020-04-08 15:04 UTC, obonaventure commented on _posts/2020-04-08-Alias.md
> +Cela est assez chronophage et ennuyant, et les alias permettent de recourir à ce problème. Ils nous permettront par exemple d'écrire directement
je mettrais éviter ou résoudre plutôt que "recourir à"

2020-04-08 15:04 UTC, obonaventure commented on _posts/2020-04-08-Alias.md
> +	**Attention, cet alias est à utiliser avec précaution !**
Cela suppose d'avoir un très bon fichier .gitignore ...

2020-04-08 15:26 UTC, dhoutart commented on _posts/2020-04-08-Alias.md
> +L'utilisation des _**alias**_ dans le shell (bash pour les explications qui suivent) est un outil à connaître absolument par la simplicité de sa mise en place et par le temps qu'il fait gagner quand
Résolu, voir commit 3b71a025c1f1439f96b71fa3cf1a40766d2e33ff

2020-04-08 15:26 UTC, dhoutart commented on _posts/2020-04-08-Alias.md
> +Cela est assez chronophage et ennuyant, et les alias permettent de recourir à ce problème. Ils nous permettront par exemple d'écrire directement
Résolu, voir commit 3b71a025c1f1439f96b71fa3cf1a40766d2e33ff

2020-04-08 15:26 UTC, dhoutart commented on _posts/2020-04-08-Alias.md
> +	**Attention, cet alias est à utiliser avec précaution !**
Résolu, voir commit 3b71a025c1f1439f96b71fa3cf1a40766d2e33ff

2020-04-09 08:09 UTC, merged

2020-04-09 08:09 UTC, obonaventure commented
Merci pour cet article, je l'intègre au blog. Les problèmes des tests d'intégration sont liés à l'orthographe de certains mots que je vais corriger.